name: Release new version

on:
  push:
    tags:
      - v*.*.*

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./NGPlusSaveMetadataChecker.vcxproj
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}

    - name: Generate hashcode
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        $hash = Get-FileHash -Algorithm SHA256 -Path ./x64/Release/NGPlusSaveMetadataChecker.exe
        $hash | Format-List
        $only_hash = $hash | ForEach-Object { $_.Hash }
        echo "NGPLUS_SAVE_DEBUGGER_SHA256=${only_hash}" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

    - name: Upload build to releases
      uses: softprops/action-gh-release@v2.0.4
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        append_body: true
        body: |
          ### SHA256 of release:
          - ${{env.NGPLUS_SAVE_DEBUGGER_SHA256}}
        files: | 
          ./x64/Release/NGPlusSaveMetadataChecker.exe